# Generated by Django 6.0.3 on 2026-04-03 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='account_type',
            field=models.CharField(choices=[('SAVINGS', 'Savings'), ('CURRENT', 'Current'), ('BUSINESS', 'Business')], default='test', max_length=10),
            preserve_default=False,
        ),
    ]
