# Generated by Django 6.0.3 on 2026-04-03 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_bankaccount_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_type',
            field=models.CharField(choices=[('SAVINGS', 'Savings'), ('CURRENT', 'Current'), ('BUSINESS', 'Business')], default='SAVINGS', max_length=10),
        ),
    ]
