# Generated by Django 6.0.3 on 2026-04-06 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0004_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAW', 'Withdraw'), ('TRANSFER', 'Transfer')], max_length=10),
        ),
    ]
